name: Deploy

on:
  push:
    branches:
      - '**' # Matches any branch


jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Deploy using secret key
        env:
          DEPLOY_KEY: ${{ secrets.DEPLOY_KEY }}
        run: echo "Deploying with DEPLOY_KEY"
      